services:
  commit-email-bot:
    build: .
    image: commit-email-bot:latest
    ports:
      - "80:80"
      - "443:8888"
    volumes:
      - ./persist:/app/persist
    environment:
      TLS_HOSTNAME: commit-emails.xyz
      DOTENV_PRIVATE_KEY_PRODUCTION: $DOTENV_PRIVATE_KEY_PRODUCTION
