services:
  commit-email-bot:
    build: .
    image: tchajed/commit-email-bot:latest
    ports:
      - "80:80"
      - "443:8888"
    volumes:
      - ${PERSIST_LOCAL_PATH:-./persist}:/app/persist
    environment:
      TLS_HOSTNAME: ${TLS_HOSTNAME:-commit-emails.xyz}
      DOTENV_PRIVATE_KEY_PRODUCTION: $DOTENV_PRIVATE_KEY_PRODUCTION
      PERSIST_PATH: /app/persist
      EMAIL_STDOUT: ${EMAIL_STDOUT}
